spring:
  application:
    name: spring-boot-with-spring-security-token-sample
  datasource:
    initialization-mode: never
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:in_memory_shopping_db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

# config tomcat server
server:
  port: 8081
  #address: 0.0.0.0
  servlet:
    context-path: /
  tomcat:
    max-swallow-size: 50MB
    max-http-form-post-size: 50MB

# spring actuator
management:
  endpoint:
    health:
      show-details: when_authorized
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,shutdown